A bunch of tiny doc string fixes
Qiskit/qiskit-dynamics pull request #134
Opened 2022-10-15 23:09 UTC by ihincks

### Summary

This is a non-comprehensive set of tiny fixes for the docstrings.

### Details and comments

2022-10-15 23:09 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/Qiskit/qiskit-dynamics?pullRequest=134) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/Qiskit/qiskit-dynamics?pullRequest=134) before we can accept your contribution.<br/><hr/>**Ian Hincks** seems not to be a GitHub user. You need a GitHub account to be able to sign the CLA. If you have already a GitHub account, please [add the email address used for this commit to your account](https://help.github.com/articles/why-are-my-commits-linked-to-the-wrong-user/#commits-are-not-linked-to-any-user).<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/Qiskit/qiskit-dynamics?pullRequest=134) it.</sub>

2022-10-15 23:57 UTC, mtreinish commented
The issue with the cla is that the author email address on the git commit is `ihincks@Ians-MacBook-Pro.local`. The cla checks the email addresses associated with your github account to validate the authors of all the commits in PR branch have signed the cla. To fix this you'll need to reset the authorship of the git commit to an email address associated with your github account. Basically something like:

```
git config - - global user.email email@address.com
git commit - -amend - - reset-author
```

Then you'll need to force push the branch to your fork and that should update it so the cla bot will see you wrote the commit

2022-10-17 14:00 UTC, DanPuzzuoli requested changes
Carried over the same change request from the previous iteration of this PR.

2022-10-17 14:00 UTC, DanPuzzuoli commented on qiskit_dynamics/models/rotating_frame.py
> +        r"""Take a state out of the rotating frame, i.e. return ``(tF) @ y``.
```suggestion
        r"""Take a state out of the rotating frame, i.e. return ``exp(tF) @ y``.
```

2022-10-17 14:11 UTC, DanPuzzuoli approved these changes

2022-10-17 15:17 UTC, merged