Fix pulse to signal converter
Qiskit/qiskit-dynamics pull request #164
Opened 2022-12-13 03:54 UTC by to24toro

### Summary
This PR fixes the behavior of InstructionToSignals.get_signals.

### Details and comments
Fix the behavior of get_signals when using Delay in qiskit-pulse.
Add a phase accumulation term when using shift or set frequency in qiskit-pulse.

2022-12-13 03:55 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/Qiskit/qiskit-dynamics?pullRequest=164) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/Qiskit/qiskit-dynamics?pullRequest=164) before we can accept your contribution.<br/><hr/>**Kento Ueda** seems not to be a GitHub user. You need a GitHub account to be able to sign the CLA. If you have already a GitHub account, please [add the email address used for this commit to your account](https://help.github.com/articles/why-are-my-commits-linked-to-the-wrong-user/#commits-are-not-linked-to-any-user).<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/Qiskit/qiskit-dynamics?pullRequest=164) it.</sub>

2022-12-13 17:07 UTC, DanPuzzuoli requested changes
Thanks for these very important fixes.

I've added a couple of comments in the code, but aside from this, I think we need more tests to make sure that the behaviour you're putting in is actually being implemented. The test you've added is a good test, but it doesn't test the interaction between delays and `SetFrequency`/`ShiftFrequency` instructions. Can you add another test like `test_delay`, but where you do `ShiftFrequency` before and after the delay, to test the correct signal is being generated as in the Ramsi experiment? I'd also like to see tests with multiple `ShiftFrequency` and `SetFrequency` instructions. 

I also think we should update the doc string for `InstructionToSignals` to be very clear about what rules it is using to generate samples. You could either do this here, or it can be done in a subsequent PR.

2022-12-14 06:31 UTC, to24toro commented on qiskit_dynamics/pulse/pulse_to_signals.py
> +                )
I adapt this to `phase_accumulations[chan] -= inst.frequency * start_sample * self._dt`.
Do I need to change the sign to plus ?

2022-12-14 08:46 UTC, to24toro commented
Thank you for reviewing.
I added tests about the combination of ShiftFrequency, Set Frequency, and delay to confirm a phase accumulation. It may be a little bit too specific...

2022-12-14 08:52 UTC, to24toro commented on test/dynamics/pulse/test_pulse_to_signals.py
> +        dt = 0.222
I defined variables often used here. We can find other frequently used number in other tests. So We can define these variables often used at setUp method.  I may refactor after merging this PR.

2022-12-14 16:17 UTC, DanPuzzuoli commented on qiskit_dynamics/pulse/pulse_to_signals.py
> +                )
No that's okay - you can actually leave both as is - it was only a slight preference on my part, but doesn't really matter.

2022-12-14 17:12 UTC, DanPuzzuoli requested changes
Nice changes to the tests - I think this pretty much covers everything.

I found the tests somewhat confusing to verify; the parentheses were a bit confusing and how the phase accumulation was calculated was not explicit. I've just opened a PR to your branch that changes the tests to how I'd like them to look. 

If you can take a look at that and merge it if it looks fine, then the only things left to do are:
- It seems you need to sign the CLA still. 
- Make sure this PR passes the linter.

2022-12-15 05:15 UTC, to24toro commented
Thank you for improving my codes.
Definitely,  predefining phase_accumulation and freq_shift is more readable.

I fixed the author committing to this PR because I used the wrong one.

2022-12-15 18:01 UTC, DanPuzzuoli submitted a review, later dismissed
I just made some final documentation changes, and it looks good to me! Will merge once tests pass.

2022-12-15 18:06 UTC, DanPuzzuoli approved these changes

2022-12-15 19:27 UTC, merged