Feature/add docs for jax jit
Qiskit/qiskit-dynamics pull request #194
Opened 2023-02-27 09:09 UTC by to24toro

### Summary

This tutorial and user guide are related to https://github.com/Qiskit/qiskit-dynamics/pull/149.
In the user guide, 
- show some pulses using ScalableSymbolicPulse.
- jax-jit these pulses.

The tutorial shows the optimization of a single X gate defined by pulse schedulers.
It is much overlapping with the configuration of https://qiskit.org/documentation/dynamics/tutorials/optimizing_pulse_sequence.html .
Whether or not merging this PR depends on the discussion.

### Details and comments
Currently, a new class ScalableSymbolicPulse which is a subclass of SymbolicPuse and assumed to hava a scalable form was introduced. So I use this class in this PR. However, I use the SymbolicPulse in https://github.com/Qiskit/qiskit-dynamics/pull/149. I would like to discuss which we should use.

2023-03-01 21:14 UTC, DanPuzzuoli requested changes
I've given direct comments on the user guide. I think it is good, but just needs to be a bit simplified.

For the tutorial, I think it can be much more simplified. I don't think it is necessary to have separate 2-A, ..., 6-A and 2-B, ..., 6-B sections. I was thinking the original 2-6 steps could be kept as they are, and a single additional section numbered 7 (with subsections) could be added for doing the `ScalableSymbolicPulse` optimization, using the same model and fidelity function as sections 2-6. I realize that you are wanting to use DRAG, the relevance of which requires using a transmon model, but for the simplicity of the presentation I think it makes sense to just use the qubit model of section 2.

2023-03-01 22:56 UTC, to24toro commented on docs/userguide/how_to_use_pulse_schedule_for_jax_jit.rst
> +    for JAX.
make senses.

2023-03-01 23:09 UTC, to24toro commented on docs/userguide/how_to_use_pulse_schedule_for_jax_jit.rst
> +2. How to generate a variety of pulses by ``ScalableSymbolicPulse``
Certainly, it may be too much to users to show 3 patterns specially.

2023-03-02 03:03 UTC, to24toro commented on docs/userguide/how_to_use_pulse_schedule_for_jax_jit.rst
> +Using a Gaussian pulse as an example, jit compilation is executed as follows.
Thanks for adding the sentence. Modified at https://github.com/Qiskit/qiskit-dynamics/pull/194/commits/b7ef506fb906a3b9763c99c0b40158f4fafd95ad.

2023-03-03 23:05 UTC, DanPuzzuoli requested changes
This current iteration is looking good. I've suggestions for edits to the text.

Aside from these suggestions, one thing you should do is add direct sphinx references to classes/functions in Terra. E.g. in the [`DynamicsBackend` docs](https://github.com/Qiskit/qiskit-dynamics/blob/c1f160a9e6dfbbb5937ba393cd0218c0bd71f962/qiskit_dynamics/backend/dynamics_backend.py#L65), there are references to objects in terra, such as:
```
:class:`~qiskit.providers.backend.BackendV2`
```

(As an aside, in case you haven't seen this before, [this line in docs/conf.py](https://github.com/Qiskit/qiskit-dynamics/blob/c1f160a9e6dfbbb5937ba393cd0218c0bd71f962/docs/conf.py#L74) sets up the `intersphinx` package for linking documentation to other packages. In this case it is only `qiskit`, but `qiskit_experiments` is also being added in #193 .)

So, e.g., all of the references to ``ScalableSymbolicPulse`` can be turned into links to the API documentation for the class. I think you should even be able to link to the qiskit pulse module using
```
:mod:`~qiskit.pulse`
```
(not sure if this is correct syntax, but something like this should work).

2023-03-07 03:02 UTC, DanPuzzuoli requested changes
Some final small changes. After these I will approve.

2023-03-07 03:02 UTC, DanPuzzuoli commented on docs/tutorials/optimizing_pulse_sequence.rst
> +We can draw the optimized pulse, whose parameters are retrieved by :math:`opt_results.x`.
```suggestion
We can draw the optimized pulse, whose parameters are retrieved by ``opt_results.x``.
```

2023-03-08 06:53 UTC, to24toro commented on docs/tutorials/optimizing_pulse_sequence.rst
> +We can draw the optimized pulse, whose parameters are retrieved by :math:`opt_results.x`.
Fix at https://github.com/Qiskit/qiskit-dynamics/pull/194/commits/83684a225937efdbca0a252d3a1bf7e08cf0bab8.

2023-03-08 06:53 UTC, to24toro commented on docs/tutorials/optimizing_pulse_sequence.rst
> +Although qiskit pulse provides a :class:`~qiskit.pulse.library.GaussianSquare`, this class is not JAX compatible.
Fix at https://github.com/Qiskit/qiskit-dynamics/pull/194/commits/83684a225937efdbca0a252d3a1bf7e08cf0bab8.

2023-03-08 06:53 UTC, to24toro commented on docs/tutorials/optimizing_pulse_sequence.rst
> +We set the initial values of `sigma` and `width` for the optimization as :math:`initial_params = np.array([10, 10,])`.
Fix at https://github.com/Qiskit/qiskit-dynamics/pull/194/commits/83684a225937efdbca0a252d3a1bf7e08cf0bab8.

2023-03-08 06:53 UTC, to24toro commented on docs/tutorials/optimizing_pulse_sequence.rst
> +    initial_params = np.array([10, 10,])
Fix at https://github.com/Qiskit/qiskit-dynamics/pull/194/commits/83684a225937efdbca0a252d3a1bf7e08cf0bab8.

2023-03-08 17:02 UTC, DanPuzzuoli approved these changes

2023-03-08 17:45 UTC, merged